language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "4"
  - "5"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
services:
  - redis-server
  - mongodb
notifications:
  email:
    - neuhaus@entenhausen.io
